version: '3.3'

services:
  frappe:
    image: pipech/erpnext-docker-debian:mas-py3-latest
    deploy:
      replicas: 1
    volumes:
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true
    env_file:
      - ./env/frappe_app.env
    command: ["/home/frappe/production_config/entrypoint_prd.sh"]
    labels:
      - "traefik.enable=true"
      # - "traefik.frontend.rule=Host:example1.com, example2.com" [Separate with comma]
      - "traefik.frontend.rule=Host:example1.com"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - frappe_db
      - default

  redis-cache:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-cache-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    networks:
      - default

  redis-queue:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-queue-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    networks:
      - default

  redis-socketio:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-socketio-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    networks:
      - default

volumes:
  frappe-sites-volumes:
  frappe-logs-volumes:

configs:
  redis-cache-conf:
    file: ./conf/redis-conf/redis_cache.conf
  redis-queue-conf:
    file: ./conf/redis-conf/redis_queue.conf
  redis-socketio-conf:
    file: ./conf/redis-conf/redis_socketio.conf

networks:
  traefik_proxy:
    external: true
  frappe_db:
    external: true
